/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserRoundPaymentResponse } from '../../models/user-round-payment-response';

export interface GetUserRoundPayments$Params {
  'ekub-id': string;
  version: number;
}

export function getUserRoundPayments(http: HttpClient, rootUrl: string, params: GetUserRoundPayments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserRoundPaymentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getUserRoundPayments.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
    rb.query('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserRoundPaymentResponse>>;
    })
  );
}

getUserRoundPayments.PATH = '/payments/user/round/{ekub-id}';
