/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUserRoundPaymentResponse } from '../../models/page-response-user-round-payment-response';

export interface GetUserRoundPayments$Params {
  'ekub-id': string;
  page?: number;
  size?: number;
}

export function getUserRoundPayments(http: HttpClient, rootUrl: string, params: GetUserRoundPayments$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserRoundPaymentResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserRoundPayments.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUserRoundPaymentResponse>;
    })
  );
}

getUserRoundPayments.PATH = '/payments/user/round/{ekub-id}';
