/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EkubPaymentStatusResponse } from '../../models/ekub-payment-status-response';

export interface GetEkubPaymentStatus$Params {
  'ekub-id': string;
}

export function getEkubPaymentStatus(http: HttpClient, rootUrl: string, params: GetEkubPaymentStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EkubPaymentStatusResponse>>> {
  const rb = new RequestBuilder(rootUrl, getEkubPaymentStatus.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EkubPaymentStatusResponse>>;
    })
  );
}

getEkubPaymentStatus.PATH = '/payments/payment-status/{ekub-id}';
