/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponse } from '../../models/user-response';

export interface GetRoundWinner$Params {
  'ekub-id': string;
  'round-no': number;
}

export function getRoundWinner(http: HttpClient, rootUrl: string, params: GetRoundWinner$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, getRoundWinner.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
    rb.query('round-no', params['round-no'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

getRoundWinner.PATH = '/ekub-users/winner/{ekub-id}';
