/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberDetailResponse } from '../../models/member-detail-response';

export interface GetMemberDetail$Params {
  'ekub-id': string;
  version: number;
}

export function getMemberDetail(http: HttpClient, rootUrl: string, params: GetMemberDetail$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MemberDetailResponse>>> {
  const rb = new RequestBuilder(rootUrl, getMemberDetail.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
    rb.path('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MemberDetailResponse>>;
    })
  );
}

getMemberDetail.PATH = '/ekub-users/member-detail/{ekub-id}/{version}';
