server:
  port: 8088
  tomcat:
    max-connections: 10000
    accept-count: 10000
#    threads:
#      max: 10
spring:
  application:
    name: alem-ekub-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/alem_ekub_db
    username: hab
    password: password
    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/alem-ekub"

keycloak:
  auth-server-url: http://localhost:9090
  realm: alem-ekub
  client-id: backend-service
  client-secret: Ot54gUJCZcGKo3wm4z2xBu6OvMFoX63G

application:
  server:
    url: ${SERVER_URL:http://localhost:8088/api/v1}
  cors:
    origins: ${ALLOWED_ORIGINS:http://localhost:4200}
  file:
    path: ${FILE_PATH:./photo}

