/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EkubRequest {
  amount: number;
  description: string;
  frequencyInDays: number;
  id?: string;
  isActive?: boolean;
  isArchived?: boolean;
  isExclusive?: boolean;
  name: string;
  nextDrawDateTime?: string;
  penaltyPercentPerDay: number;
  startDateTime?: string;
  totalAmount?: number;
  type: string;
}
