/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EkubStatusResponse {
  startDate?: string;
  totalMembers?: number;
  winnersCount?: number;
}
