/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EkubResponse {
  amount?: number;
  description?: string;
  frequencyInDays?: number;
  id?: string;
  isActive?: boolean;
  isArchived?: boolean;
  isExclusive?: boolean;
  lastDrawDateTime?: string;
  mpesaAccountNumber?: number;
  name?: string;
  nextDrawDateTime?: string;
  penaltyPercentPerDay?: number;
  roundNumber?: number;
  startDateTime?: string;
  telebirrAccountNumber?: number;
  totalAmount?: number;
  totalMember?: number;
  type?: string;
  version?: number;
  winAmount?: number;
}
