/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EkubPaymentStatusResponse {
  hasWon?: boolean;
  roundPaymentsStatus?: Array<boolean>;
  userId?: string;
  username?: string;
}
