/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LastRoundResponse {
  id?: string;
  paid?: boolean;
  roundNumber?: number;
  version?: number;
  winnerId?: string;
  winnerUsername?: string;
}
