/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberDetailResponse {
  fullName?: string;
  guarantor?: string;
  isPaid?: boolean;
  roundNumber?: number;
  userId?: string;
  username?: string;
  version?: number;
  winRoundId?: string;
}
