/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRoundPaymentResponse } from '../models/user-round-payment-response';
export interface PageResponseUserRoundPaymentResponse {
  content?: Array<UserRoundPaymentResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
