/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentRequest {
  amount: number;
  paymentMethod: string;
  remark: string;
  roundId: string;
  toUserId?: string;
  type: 'MEMBER_PAYMENT' | 'WINNING_PAYOUT';
  userId: string;
}
