/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentResponse {
  amount?: number;
  createdDate?: string;
  ekubName?: string;
  id?: string;
  paymentMethod?: string;
  remark?: string;
  roundNumber?: number;
  roundVersion?: number;
  toUsername?: string;
  type?: 'MEMBER_PAYMENT' | 'WINNING_PAYOUT';
  username?: string;
}
