/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  ekubIds?: Array<string>;
  email?: string;
  enabled?: boolean;
  firstName: string;
  id?: string;
  lastName: string;
  password?: string;
  phoneNumber: string;
  profession: string;
  remark?: string;
  username: string;
}
