/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  ekubIdList?: Array<string>;
  ekubNameList?: Array<string>;
  email?: string;
  enabled?: boolean;
  firstname?: string;
  fullName?: string;
  guarantors?: Array<string>;
  id?: string;
  idCardImageUrl?: string;
  lastname?: string;
  phoneNumber?: string;
  profession?: string;
  profilePicUrl?: string;
  remark?: string;
  username?: string;
}
