/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserPendingPaymentResponse {
  amount?: number;
  endDateTime?: string;
  equbName?: string;
  roundId?: string;
  roundNumber?: number;
}
