/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LastRoundResponse } from '../../models/last-round-response';

export interface GetLastRound$Params {
  'ekub-id': string;
  version: number;
  'round-no': number;
}

export function getLastRound(http: HttpClient, rootUrl: string, params: GetLastRound$Params, context?: HttpContext): Observable<StrictHttpResponse<LastRoundResponse>> {
  const rb = new RequestBuilder(rootUrl, getLastRound.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
    rb.path('version', params.version, {});
    rb.path('round-no', params['round-no'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LastRoundResponse>;
    })
  );
}

getLastRound.PATH = '/rounds/{ekub-id}/{version}/{round-no}';
