/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EkubResponse } from '../../models/ekub-response';

export interface GetEkubById$Params {
  'ekub-id': string;
}

export function getEkubById(http: HttpClient, rootUrl: string, params: GetEkubById$Params, context?: HttpContext): Observable<StrictHttpResponse<EkubResponse>> {
  const rb = new RequestBuilder(rootUrl, getEkubById.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EkubResponse>;
    })
  );
}

getEkubById.PATH = '/ekubs/{ekub-id}';
