/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EkubStatusResponse } from '../../models/ekub-status-response';

export interface GetEkubStatus$Params {
  'ekub-id': string;
  version: number;
}

export function getEkubStatus(http: HttpClient, rootUrl: string, params: GetEkubStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<EkubStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getEkubStatus.PATH, 'get');
  if (params) {
    rb.path('ekub-id', params['ekub-id'], {});
    rb.path('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EkubStatusResponse>;
    })
  );
}

getEkubStatus.PATH = '/ekubs/ekub-status/{ekub-id}/{version}';
