name: alem ekub backend pipeline

on:
  push:
    branches:
      - pipeline
    paths:
      - alem-ekub-api/**
      - docker/backend/**
      - 'docker-compose.yml'
      - .github/workflows/*-backend.yml
jobs:
  compile:
    runs-on: ubuntu-latest
    name: compile-project
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'corretto'

      - name: compile project
        run: |
          cd alem-ekub-api
          ./mvnw clean compile

  build:
    runs-on: ubuntu-latest
    name: build backend
    needs: [ compile ]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'corretto'

      - name: build project
        run: |
          cd alem-ekub-api
          ./mvnw clean package

  build-image:
    runs-on: ubuntu-latest
    name: build docker image
    needs: [build]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'corretto'

      - name: build project
        run: |
          cd alem-ekub-api
          ./mvnw clean package

      - name: extract project version
        id: extract_version
        run: |
          cd alem-ekub-api
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: alem-ekub-api
          file: docker/backend/Dockerfile
          push: true
          platform: linux/amd64
          tags: ${{secrets.DOCKERHUB_USERNAME}}/alem-ekub-api:${{ steps.extract_version.outputs.VERSION }},${{secrets.DOCKERHUB_USERNAME}}/alem-ekub-api:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
  
