name: Alem Frontend Pipeline

on:
  push:
    branches:
      - pipeline
    paths:
      - alem-ekub-ui/**
      - docker/frontend/**
      - 'docker-compose.yml'
      - .github/workflows/*-frontend.yml

jobs:
  build-image:
    name: build frontend docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: extract project version
        id: extract_version
        run: |
          cd alem-ekub-ui
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: alem-ekub-ui
          file: docker/frontend/Dockerfile
          push: true
          platform: linux/amd64
          tags: ${{secrets.DOCKERHUB_USERNAME}}/alem-ekub-ui:${{ steps.extract_version.outputs.VERSION }},${{secrets.DOCKERHUB_USERNAME}}/alem-ekub-ui:latest
